# Site Settings
theme: bulma-clean-theme
title: Eclipsta Studio
tagline:
email: 
description: >
  Onde a luz encontra a forma.
baseurl: ""
url: "https://"
permalink: pretty
favicon: "/img/Eclipsta.svg"
gh_sponsor: 
#hide_share_buttons: true
fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr
force_theme: dark

langs:
  - pt
  - en
lang: pt
locale: pt_BR
timezone: America/Sao_Paulo

paginate: 10
paginate_path: "/blog/page:num"

disqus:
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname:

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - jstudio3design

livereload: true

sass:
  style: compressed
  source_dir: _sass
  # load_paths: 
    # - node_modules

#google_analytics: UA-code-here
#cookie_policy: /cookie-policy/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Eclipsta Studio"
      layout: post
      image:
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

collections:
  products: 
    output: true
    layout: product
    image: 
    show_sidebar: false

social: